@baseUrl = http://localhost:3001


# FAQ

### create faq
POST {{baseUrl}}/faq/
Content-Type: application/json

{
    "question": "O que é considerado no cálculo do meu seguro?",
    "answer": "O preço é calculado com base no seu perfil de risco (idade, histórico de condução, localização), as características do bem segurado (modelo, ano) e as coberturas que você escolheu.",
    "isActive": true
}


### update faq
PATCH {{baseUrl}}/faq/4
Content-Type: application/json

{
    "question": "O que é considerado no cálculo do meu seguro?",
    "answer": "O preço é calculado com base no seu perfil de risco.",
    "isActive": true
}


### find all
GET {{baseUrl}}/faq/
