@baseUrl = "http://localhost:3000"
@authToken = {{authenticate.response.body.accessToken}}
@refreshToken = {{authenticate.response.body.refreshToken}}

### Create a new user

POST {{baseUrl}}/users/create
Authorization: {{authToken}}
Content-Type: application/json

{
    "name": "Luigi",
    "passwordHash": "senha123"
}

### Find a user by ID
GET {{baseUrl}}/users/findone/1

### Login
@name authenticate 
POST {{baseUrl}}/auth/login
Content-Type: application/json 

{
    "name": "Luigi",
    "password": "senha123"
}
