services:
  api:
    container_name: nest-api
    build:
      context: .
      target: builder
    command: npm run start:dev
    env_file:
      - .env
    ports:
      - '3001:3000' # Mapeia a porta 3001 do host para 3000 do contêiner
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
    networks:
      - backend-network
    user: "${UID}:${GID}"

  db:
    container_name: postgres-db
    image: postgres:15-alpine
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge

volumes:
  postgres_data: