export enum Brands {
  'Acura',
  'Audi',
  'BMW',
  'Chevrolet',
  'Citroen',
  'Fiat',
  'Ford',
  'Honda',
  'Hyundai',
  'KIA',
  'Land Rover',
  'Lexus',
  'Mazda',
  'Mercedes',
  'Mitsubishi',
  'Nissan',
  'Peugeot',
  'Porsche',
  'Renault',
  'Suzuki',
  'Toyota',
  'Volkswagen',
  'Volvo'
}

export const BrandsWeight = {
  'Acura': 0,
  'Audi': 1.3,
  'BMW': 1.6,
  'Chevrolet': 0.4,
  'Citroen': 0.6,
  'Fiat': 0.3,
  'Ford': 0.8,
  'Honda': 0.5,
  'Hyundai': 0.6,
  'KIA': 0.6,
  'Land Rover': 2,
  'Lexus': 1,
  'Mitsubishi': 1,
  'Nissan': 0.5,
  'Peugeot': 0.8,
  'Porsche': 2,
  'Renault': 0.6,
  'Suzuki': 0.6,
  'Toyota': 0.5,
  'Volkswagen': 0.4,
  'Volvo': 1
}as const;