export enum Brands {
  'Acura' = 1,
  'Audi' = 6,
  'BMW' = 7,
  'Chevrolet' = 23,
  'Citroen' = 13,
  'Fiat' = 21,
  'Ford' = 22,
  'Honda' = 25,
  'Hyundai' = 26,
  'KIA' = 31,
  'Land Rover' = 33,
  'Lexus' = 34,
  'Mazda' = 38,
  'Mercedes' = 39,
  'Mitsubishi' = 41,
  'Nissan' = 43,
  'Peugeot' = 44,
  'Porsche' = 47,
  'Renault' = 48,
  'Suzuki' = 55,
  'Toyota' = 56,
  'Volkswagen' = 59,
  'Volvo' = 58
}

export const BrandsWeight = {
  'Acura': 0,
  'Audi': 1.3,
  'BMW': 1.6,
  'Chevrolet': 0.4,
  'Citroen': 0.6,
  'Fiat': 0.3,
  'Ford': 0.8,
  'Honda': 0.5,
  'Hyundai': 0.6,
  'KIA': 0.6,
  'Land Rover': 2,
  'Lexus': 1,
  'Mitsubishi': 1,
  'Nissan': 0.5,
  'Peugeot': 0.8,
  'Porsche': 2,
  'Renault': 0.6,
  'Suzuki': 0.6,
  'Toyota': 0.5,
  'Volkswagen': 0.4,
  'Volvo': 1
}as const;

export const carBrands = [
    { code: 1, name: 'Acura' },
    { code: 6, name: 'Audi' },
    { code: 7, name: 'BMW' },
    { code: 23, name: 'Chevrolet' },
    { code: 13, name: 'Citroen' },
    { code: 21, name: 'Fiat' },
    { code: 22, name: 'Ford' },
    { code: 25, name: 'Honda' },
    { code: 26, name: 'Hyundai' },
    { code: 31, name: 'KIA' },
    { code: 33, name: 'Land Rover' },
    { code: 34, name: 'Lexus' },
    { code: 38, name: 'Mazda' },
    { code: 39, name: 'Mercedes' },
    { code: 41, name: 'Mitsubishi' },
    { code: 43, name: 'Nissan' },
    { code: 44, name: 'Peugeot' },
    { code: 47, name: 'Porsche' },
    { code: 48, name: 'Renault' },
    { code: 55, name: 'Suzuki' },
    { code: 56, name: 'Toyota' },
    { code: 59, name: 'Volkswagen' },
    { code: 58, name: 'Volvo' }
] as const;